# Generated by Django 5.1.2 on 2024-12-26 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_building_appartment_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='appartment',
            name='image',
            field=models.ImageField(null=True, upload_to='images/appartments/'),
        ),
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(null=True, upload_to='images/buildings/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_account', to='app.account'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/customers/'),
        ),
    ]
