# Generated by Django 5.1.2 on 2024-12-27 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_building_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appartment_owner', to='app.customer'),
        ),
        migrations.AddField(
            model_name='appartment',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appartment_renter', to='app.customer'),
        ),
    ]
